### PR TITLE
Move ingress defaultBackend out of the templates

### PR DESCRIPTION
**Pull request by marcemv90**
# Motivation

The current [ingress.yaml](https://github.com/featurehub-io/featurehub-install/blob/be5bc47583ef1518d325612cede15385c84f81e9/helm/featurehub/templates/ingress.yaml#L22-L26) template has the `defaultBackend` configuration hardcoded:

```yaml
  defaultBackend:
    service:
      name: {{ include "featurehub.managementRepository.name" . }}
      port:
        name: http
```

The trade-off of having this piece of code hard coded is that all URLs matching the Load Balancer used by the ingress controller but not matching any Kubernetes ingress host will make the request fall into the `defaultBackend`, which in some cases is not desired. Example follows:

image

# Proposed solution

To make it parametrizable and retro compatible is just enough to move the hardcoded piece of code out of the templates and read it from the values instead. Note that this keeps compatibility with the previous setup:

```yaml
ingress:
  defaultBackend:
    service:
      name: management-repository
      port:
        name: http
```

If a particular deployment wants to disable it, just set the `.Values.ingress.defaultBackend` to an empty map:

```yaml
ingress:
  defaultBackend: []
```

This PR also removes the `.Values.version` field, which apparently was not used.

I hope you consider merging this PR, it would be great.

Thanks for the hard work!

Regards.

### CODE REVIEW

**Comment by rvowles** [comment]
Hi Marcelo, thanks for your contribution!

I think it would be ok if we had the default configuration have this work out of the box in kinD - my preference is that when people follow the instructions in the readme, they get what is expected, even if it is not suitable for production. If the PR could be updated so that the default is that it has your recommended ingres configuration, but adds to the documentation what to do if you don't want it, that would be very much appreciated!

**Comment by marcemv90** [comment]
Hello @rvowles , thanks for your comments.

I've just updated the default  Chart `values.yaml` to work the same way as it used to do, so no configuration changes are needed if somebody wants to run it locally, but still able to disable it or change it if desired.

I've also added the `helm-docs` generated README.md to the chart to easily see all the configuration parameters in a single place. The ingress `defaultBackend` configuration setting is also documented there.

Let me know if something else needs to be changed or if it is just fine as it is :) 

Thanks!

**Comment by rvowles** [comment]
Hi @marcemv90 - there is another PR that has merged ahead of yours, I can fix your changes on top of `main` or you can have a go if you like? Once the conflicts are resolved I will merge it in!

**Comment by rvowles** [comment]
The lint docs process failed? Thanks for fixing the conflict! https://github.com/featurehub-io/featurehub-install/runs/5431163371?check_suite_focus=true

**Comment by marcemv90** [comment]
Hello @rvowles, I just resolved the conflicts, I also set the Chart version to 2.0.1. Feel free to merge.

On the next days I'll try to raise a new PR to make a few more improvements to the Chart.

Many thanks!

**Comment by rvowles** [comment]
@marcemv90 so i should merge it even with the lint docs failing? I'm ok to do that.

**Comment by rvowles** [comment]
@marcemv90 still seems unhappy?

**Comment by rvowles** [comment]
is there something wrong with the version of helm-docs the workflow is using?

**Comment by marcemv90** [comment]
I think it is failing because of the `git diff --exit-code` that's run as part of the `helm-docs.sh` script. Not sure of the purpose of that command there, but as that README is a new file, I think is going to complain all the time.

Do you wan't me to remove that new README.md file, or should I remove the `git diff` line from the `helm-docs.sh`?

**Comment by rvowles** [comment]
Remove the line I think, i don't think it makes a lot of sense either.

**Comment by marcemv90** [comment]
Hello @rvowles, the `git diff` line has been removed.

**Comment by rvowles** [comment]
yay! thanks for your work @marcemv90 🥇 !

**Comment by marcemv90** [comment]
Great!

I hope I can do a new PR during these days to help improving the helm chart a bit more. Thanks!

**Pull request merged**
