### PR TITLE
Various chart improvements

### PR DESCRIPTION
**Pull request by naphta**
Just came to this chart to use and it had a few missing bits and issues that I saw when I used so I just went ahead and forked and made the changes.

Essentially with the topology I was planning I wanted to be able to deploy dacha and edge separately, and I noticed that the chart worked against me when I wanted to run it as two releases in the same namespace. Whilst I was in there I put a few minor fixes in around naming, updating to a third party nats and postgresql chart (at least in theory with the right values it could be used in production then), and allowed the ingress to target a service name of choice for the edge backend.

Happy to make any changes if there's a desire to merge this.

### CODE REVIEW

**Comment by rvowles** [comment]
Hi there, nice work! I'm just bringing it up but there seem to be missing docs that someone can follow? The need to install  the helm dependencies for example. Any chance you could add those and anything else you think is relevant to help people out?

**Comment by rvowles** [comment]
ok, the NATS configuration appears to not be working either... the nats.urls= property needs to be set to the urls of the NATs servers in each of the configuration files. This is what I'm getting at the moment:
```

featurehub-dacha-7c56768f48-lflpq                   0/1     Running            6          6m3s
featurehub-dacha-7c56768f48-pqfgh                   0/1     CrashLoopBackOff   5          6m3s
featurehub-edge-5fbb4dfd85-nthn5                    0/1     CrashLoopBackOff   5          6m3s
featurehub-edge-5fbb4dfd85-tmgzt                    0/1     CrashLoopBackOff   5          6m3s
featurehub-management-repository-54f58469c9-f56h2   0/1     CrashLoopBackOff   5          6m3s
featurehub-nats-0                                   3/3     Running            0          6m3s
featurehub-nats-1                                   3/3     Running            0          6m3s
featurehub-nats-2                                   3/3     Running            0          6m3s

```

**Comment by naphta** [comment]
I shall take a look, I did have it running locally but I had my nats release in a separate release with the same values.

**Comment by naphta** [comment]
> I shall take a look, I did have it running locally but I had my nats release in a separate release with the same values.

Looks like I forgot to change the default NATS host from `nats` to `featurehub-nats`, I've got it coming up locally just fine now with no values being passed in.

```sh
NAME                                                READY   STATUS    RESTARTS   AGE
featurehub-dacha-5977cb6bdf-69jkg                   1/1     Running   3          10m
featurehub-dacha-5977cb6bdf-6hbmx                   1/1     Running   3          10m
featurehub-edge-57c4d969dd-4gbs8                    1/1     Running   2          10m
featurehub-edge-57c4d969dd-sg7rg                    1/1     Running   3          10m
featurehub-management-repository-567ff88dfd-wmph4   1/1     Running   3          10m
featurehub-nats-0                                   3/3     Running   0          10m
featurehub-nats-1                                   3/3     Running   0          10m
featurehub-nats-2                                   3/3     Running   0          10m
featurehub-nats-box-78587c4478-2t2vd                1/1     Running   0          10m
featurehub-postgresql-0                             1/1     Running   0          10m
```

**Comment by rvowles** [comment]
Ok! I spent a bit of time with this tonight because I do want it in! The only remaining issue I found is that because the dacha service has been renamed to featurehub-dacha, the config in edge's configmap still points to the old name - so http://dacha - and it needs to be http://featurehub-dacha. Otherwise it works a treat!

If you could please make that mod, I will merge it straight in, and thanks for your work!

**Comment by rvowles** [comment]
Ok, I will assume its ok if I make this change.

**Comment by naphta** [comment]
@rvowles Ha, sorry. I've been out of action ill most of the week. I did plan on sorting it as soon as I got to my desk again.

**Comment by rvowles** [comment]
Hi @naphta , it's ok, it seemed a simple fix 🙂 however it has appeared to have broken the release process so I'll look at that today.

**Pull request merged**
